# CodeRabbit Configuration for Pre-Commit Reviews
# This file configures CodeRabbit to provide automated code reviews

# Global settings
language: typescript
project_type: nextjs

# Review settings
review:
  enabled: true
  pre_commit: true   # 👈 enables reviews before pushing
  rules:
    - check: code-quality
    - check: security
    - check: best-practices
  
  # Review scope
  scope:
    # Include all TypeScript/JavaScript files
    include:
      - "**/*.{ts,tsx,js,jsx}"
      - "**/*.json"
      - "**/*.md"
      - "**/*.yml"
      - "**/*.yaml"
    
    # Exclude common directories
    exclude:
      - "node_modules/**"
      - ".next/**"
      - "dist/**"
      - "build/**"
      - "coverage/**"
      - ".git/**"
      - "*.log"
      - ".env*"

# Code quality checks
quality:
  # Enable security checks
  security: true
  
  # Enable performance checks
  performance: true
  
  # Enable best practices checks
  best_practices: true
  
  # Enable accessibility checks
  accessibility: true

# Testing configuration
testing:
  # Enable test coverage analysis
  coverage: true
  
  # Test file patterns
  test_patterns:
    - "**/*.test.{ts,tsx,js,jsx}"
    - "**/*.spec.{ts,tsx,js,jsx}"
    - "**/__tests__/**"

# Security configuration
security:
  # Check for common vulnerabilities
  vulnerabilities: true
  
  # Check for secrets and API keys
  secrets: true
  
  # Check for dependency vulnerabilities
  dependencies: true

# Performance configuration
performance:
  # Check for performance anti-patterns
  anti_patterns: true
  
  # Check for memory leaks
  memory_leaks: true
  
  # Check for inefficient algorithms
  algorithms: true

# Next.js specific configuration
nextjs:
  # Check for Next.js best practices
  best_practices: true
  
  # Check for proper API route structure
  api_routes: true
  
  # Check for proper component structure
  components: true
  
  # Check for proper TypeScript usage
  typescript: true

# Supabase specific configuration
supabase:
  # Check for proper database queries
  queries: true
  
  # Check for proper RLS policies
  rls: true
  
  # Check for proper authentication patterns
  auth: true

# Custom rules for this project
custom_rules:
  # Polling app specific rules
  polling_app:
    # Check for proper poll validation
    poll_validation: true
    
    # Check for proper error handling
    error_handling: true
    
    # Check for proper audit logging
    audit_logging: true
    
    # Check for proper rate limiting
    rate_limiting: true

# Comment settings
comments:
  # Enable inline comments
  inline: true
  
  # Enable summary comments
  summary: true
  
  # Comment on pull requests
  pull_requests: true
  
  # Comment on commits
  commits: true

# Notification settings
notifications:
  # Notify on security issues
  security: true
  
  # Notify on performance issues
  performance: true
  
  # Notify on test failures
  test_failures: true

# File size limits
limits:
  # Maximum file size (in lines)
  max_file_size: 1000
  
  # Maximum function size (in lines)
  max_function_size: 50
  
  # Maximum class size (in lines)
  max_class_size: 200

# Ignore patterns
ignore:
  # Ignore generated files
  - "**/*.generated.*"
  - "**/generated/**"
  
  # Ignore configuration files
  - "**/config/**"
  - "**/.env*"
  
  # Ignore documentation that doesn't need review
  - "**/README.md"
  - "**/CHANGELOG.md"
